import i18n from "i18next";
export const data = [
  { title: "TECH TEXTILE" },
  { title: "TECH TEXTILE" },
  { title: "CONFERENCE WORK WEAR" },
  { title: "ITMF CONFERENCE" },
  { title: "CAIRO CONFERENCE APPAREL" },
  { title: "PRATOTRADE WORKSHOP" },
  { title: "INTERTEXTILE" },
  { title: "ITMA ASIA" },
  { title: "ITMA ASIA" },
  { title: "ITMA EUROPE" },
  { title: "ITMA EUROPE" },
  { title: "PRATO EXPO" },
  { title: "MILANO UNICA" },
  { title: "PREMIERE VISION" },
  { title: "LINEA PELLE" },
  { title: "COSMOPROF" },
  { title: "A+A" },
  { title: "MILIPOL" },
  { title: "MECSPE" },
  { title: "JEC" },
  { title: "Go international" },
  { title: "XVII Congresso Nazionale AIUC " },
];
