import i18n from "i18next";
import { initReactI18next } from "react-i18next";
// import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      greeting: "HOME",
      ab: "ABOUT US",
      pt: "PARTNERS",
      ser: "SERVICES",
      ex: "EXPERIENCES",
      cu: "CONTACT US",
      c: "Contacts",
      headerH: "New Horizons for your Business",
      headerP: "The ultimate solution for expanding your business worldwide.",
      sec1H1: "Along with your dreams",
      sec1P1: "SMART specializes in consulting services for all industries.",
      sec1H2: "Prestige, quality for your projects",
      sec1P2:
        "SMART develops projects with the support of highly qualified consultants, selected for their brilliant national and international experience.",
      sec1H3: "Your business everywhere, now",
      sec1P3:
        "SMART is designed to be borderless to collaborate with companies all around the globe.",
      sec1H4: "The perfect match for your needs",
      sec1P4:
        "SMART does not provide pre-packaged solutions, but implements a specific development plan, based on the customer is needs.",
      sec1H5: "The ecogreen choice",
      sec1P5:
        "SMART believes in new technologies, and turns to the best markets to supply you with the best services to minimize the environmental impacts.",
      sec1H6: 'Unleashing the Power of AI',
      sec1p6: "SMART Revolutionizes Digital Workflows for all projects.",

      ad: 'Headquarter: Viale Vittorio Veneto 80 presso Studio G.B., 59100 Prato (PO), Italia',
      ad1: 'Office: Via G. Meoni 11, 59100 Prato (PO), Italia',
      ab_d1:
        "SMART is a revolutionary company created in March 2015 by visionary Emanuele Cecchi, with the goal of enhancing businesses worldwide.",
      ab_d2:
        "We provide a diverse range of services to our clients, counting on a team of extensively qualified consultants from various countries. They are chosen for their extensive expertise in their respective fields and their adept problem-solving abilities, along with partnerships with SMART is international collaborators.",
      ab_d3:
        "Our consultants engage closely with clients throughout every phase of their operations, collaborating from the very beginning to develop the most tailored improvement strategies to create opportunities of growth.",
      sec1_end1: "Ready to expand your horizons?",
      sec1_end2: "Make the SMART choice.",
      ab_partner: "Our Partners",
      ab_manager: "Our Country Managers",
      ser_title1: "Industrial Consultancy",
      ser_desc1:
        "SMART is ready to make your business grow! The optimal approach begins with scheduling a consultation with our team to assess market possibilities and craft the most effective internationalization strategy. Our consultancy team assists companies seeking expansion and overseas development, offering qualified, integrated support in target markets.",
      ser_title2: "Temporary Export Management",
      ser_desc2:
        "A temporary export manager is a professional dedicated to guiding your company into the international market. Embedded within your company temporarily, the export manager cultivates strong relationships with other enterprises, your possible clients, facilitating connections beyond your borders. With the aid of our collaborators, partners, and country managers, we expand your horizons and guide you to your desired destinations through a dynamic internationalization process.",
      ser_title3: "Industrial Education",
      ser_desc3:
        "Emanuele Cecchi, our visionary CEO and founder of SMART, is also a brilliant university professor. With his wealth of experience, he is ready to immerse you in the world of markets and industrial management.",
      ser_endT1: "Still curious? ",
      ser_endT2: "Schedule an appointment with us now!",
      team1_name: "Emanuele Cecchi",
      team1_pos: "Founder & General Manager",
      team2_name: "Marialessandra Cecchi",
      team2_pos: "Linguist Specialist",
      team3_name: "Chiara Storai",
      team3_pos: "Export Manager",
      team4_name: "Chiara Novelli",
      team4_pos: "Export Manager",
      cun: "CONTACT US NOW",
      cun_title:
        "Fill the form here below with your request. We will contact you soon!",
      cu_detail1: "SMART s.r.l.",
      cu_detail2: "C.S. € 10.000,00 i.v.",
      cu_detail3: "P.I e C.F. n° 06532350482",
      cu_detail4: "REA 635741",
      // cu_detail5: '',
      phone: "Phone:",
      email: "Email:",
      pec: "PEC:",
      ev: "Conferences, Events, Exhibitions",
      tit1: "Frankfurt, Germany",
      tit2: "Moscow, Russia",
      tit3: "San Petersburg, Russia",
      tit4: "Hanoi, Vietnam",
      tit5: "Cairo, Egypt",
      tit6: "Shenzen, Shanghai & Beijing, China",
      tit7: "Shanghai, China",
      tit8: "Beijing & Shanghai, China",
      tit9: "Singapore, Singapore",
      tit10: "Milano, Italy",
      tit11: "Barcellona, Spain",
      tit12: "Prato, Italy",
      tit13: "Milano, Italy",
      tit14: "Paris, France",
      tit15: "Milano, Bologna, Italy",
      tit16: "Bologna, Italy",
      tit17: "Dusseldorf, Germany",
      tit18: "Paris, France",
      tit19: "Bologna, Italy",
      ser1_img1_text: 'Emanuele in a meeting with the Egyptian Minister of Industry',
      ser1_img2_text: 'Emanuele in a meeting with the Russian Minister of Industry',
      ser_head: "Emanuele Cecchi is an awarded Innovation Manager regularly member of the Italian Minister of Companies and Made in Italy (MIMIT) 's list and of Italian istitution Unioncamere.",
      map_title: "Our SMART world",
      map_desc: 'We are proud to showcase all our experiences in countries around the world',
    },
  },
  fr: {
    translation: {
      greeting: "ACCUEIL",
      ab: "DÉCOUVREZ-NOUS",
      pt: "Partenaires",
      ser: "SERVICES",
      ex: "EXPÉRIENCES",
      cu: "CONTACTEZ-NOUS",
      c: "Contacts",
      headerH: "De Nouveaux Horizons pour Votre Entreprise",
      headerP:
        "La solution ultime pour étendre votre entreprise àl échelle mondiale.",
      sec1H1: "Avec vos rêves",
      sec1P1:
        "SMART se spécialise dans les services de consultation pour tous les secteurs d activité.",
      sec1H2: "Prestige, qualité pour vos projets",
      sec1P2:
        "SMART développe des projets avec le soutien de consultants hautement qualifiés, sélectionnés pour leur brillante expérience nationale et internationale.",
      sec1H3: "Votre entreprise partout, maintenant",
      sec1P3:
        "SMART est conçu pour être sans frontières afin de collaborer avec des entreprises du monde entier.",
      sec1H4: "La correspondance parfaite pour vos besoins",
      sec1P4:
        "SMART ne fournit pas de solutions pré-emballées, mais met en œuvre un plan de développement spécifique, basé sur les besoins du client.",
      sec1H5: "La voie écologique",
      sec1P5:
        "SMART croit en les nouvelles technologies et se tourne vers les meilleurs marchés pour vous fournir les meilleurs services afin de minimiser les impacts environnementaux.",
      sec1H6: 'Libérer la Puissance de lIA',
      sec1p6: "SMART Révolutionne les Flux de Travail Numériques pour tous les projets.",
      ad: 'Siège Social: Viale Vittorio Veneto 80 chez Studio G.B., 59100 Prato (PO), Italie',
      ad1: 'Bureau: Via G. Meoni 11, 59100 Prato (PO), Italie',
      ab_d1:
        "SMART est une entreprise révolutionnaire créée en mars 2015 par le visionnaire Emanuele Cecchi, dans le but d améliorer les entreprises dans le monde entier.",
      ab_d2:
        "Nous offrons une gamme diversifiée de services à nos clients, en nous appuyant sur une équipe de consultants hautement qualifiés provenant de différents pays. Ils sont choisis pour leur vaste expérience dans leurs domaines respectifs et leurs compétences expertes en résolution de problèmes, ainsi que pour les partenariats avec les collaborateurs internationaux de SMART.",
      ab_d3:
        "Nos consultants collaborent étroitement avec les clients à chaque phase de leurs opérations, en travaillant dès le début pour développer les stratégies d amélioration les plus adaptées et créer des opportunités de croissance.",
      sec1_end1: "Prêt à élargir vos horizons ?",
      sec1_end2: "Faites le choix SMART.",
      ab_partner: "Nos Partenaires:",
      ab_manager: "Nos Responsables Pays:",
      ser_title1: "Consultance Industrielle",
      ser_desc1:
        "SMART est prêt à faire croître votre entreprise ! L'approche optimale commence par la planification d'une consultation avec notre équipe pour évaluer les possibilités de marché et élaborer la stratégie d'internationalisationla plus efficace. Notre équipe de consultance assiste les entreprises à la recherche d'expansion et de développement à l'étranger, en offrant un soutien qualifié et intégré dans les marchés cibles.",
      ser_title2: "Gestion Temporaire de l'Exportation",
      ser_desc2:
        "Un gestionnaire d'exportation temporaire est un professionnel dédié à guider votre entreprise sur le marché international. Temporairement intégré dans votre entreprise, le gestionnaire d'exportation cultive des relations solides avec d'autres entreprises, vos clients potentiels, facilitant les connexions au-delà de vos frontières. Avec l'aide de nos collaborateurs, partenaires et responsables pays, nous élargissons vos horizons et vous guidons vers les destinations souhaitées à travers un processus dynamique d'internationalisation.",
      ser_title3: "Formation Industrielle",
      ser_desc3:
        "Emanuele Cecchi, notre PDG visionnaire et fondateur de SMART, est également un brillant professeur d'université. Avec sa riche expérience, il est prêt à vous plonger dans le monde des marchés et de la gestion industrielle.",
      ser_endT1: "Toujours curieux ?",
      ser_endT2: "Prenez rendez-vous avec nous dès maintenant !",
      team1_name: "Emanuele Cecchi",
      team1_pos: "Fondateur et Directeur Général",
      team2_name: "Marialessandra Cecchi",
      team2_pos: "Spécialiste Linguistique",
      team3_name: "Chiara Storai",
      team3_pos: "Responsable Export",
      team4_name: "Chiara Novelli",
      team4_pos: "Responsable Export",
      cun: "CONTACTEZ-NOUS MAINTENANT",
      cun_title:
        "Remplissez le formulaire ci-dessous avec votre demande. Nous vous contacterons bientôt !",
      cu_detail1: "SMART s.r.l.",
      cu_detail2: "C.S. € 10.000,00 i.v.",
      cu_detail3: "P.I et C.F. n° 06532350482",
      cu_detail4: "REA 635741",
      // cu_detail5: '',
      phone: "Téléphone:",
      email: "Email:",
      pec: "PEC:",
      ev: "Conférences, Événements, Expositions",
      tit1: "Francfort, Allemagne",
      tit2: "Moscou, Russie",
      tit3: "Saint-Pétersbourg, Russie",
      tit4: "Hanoï, Vietnam",
      tit5: "Le Caire, Égypte",
      tit6: "Shenzhen, Shanghai et Pékin, Chine",
      tit7: "Shanghai, Chine",
      tit8: "Pékin et Shanghai, Chine",
      tit9: "Singapour, Singapour",
      tit10: "Milan, Italie",
      tit11: "Barcelone, Espagne",
      tit12: "Prato, Italie",
      tit13: "Milan, Italie",
      tit14: "Paris, France",
      tit15: "Milan, Bologne, Italie",
      tit16: "Bologne, Italie",
      tit17: "Düsseldorf, Allemagne",
      tit18: "Paris, France",
      tit19: "Bologne, Italie",
      ser1_img1_text: 'Emanuele lors dune réunion avec le Ministre de lIndustrie Égyptien',
      ser1_img2_text: 'Emanuele lors dune réunion avec le Ministre de lIndustrie Russe',
      ser_head: "Emanuele Cecchi est un Manager de l'innovation reconnu et régulièrement inscrit à la liste du Ministère Italien du Commerce et du Made in Italy (MIMIT) et au registre de l'institution italienne Uniocamere.",
      map_title: "Notre monde SMART",
      map_desc: 'Nous sommes fiers de montrer toutes nos expériences dans les pays du monde',
    },
  },
  it: {
    translation: {
      greeting: "HOME",
      ab: "CHI SIAMO",
      pt: "Partner",
      ser: "I nostri servizi",
      ex: "ESPERIENZE",
      cu: "CONTATTACI",
      c: "Contatti",
      headerH: "Nuovi Orizzonti per il tuo Business",
      headerP:
        "La soluzione definitiva per espandere la tua attività in tutto il mondo.",
      sec1H1: "Insieme ai tuoi sogni",
      sec1P1:
        "SMART si specializza nei servizi di consulenza per tutte le industrie.",
      sec1H2: "Prestigio, qualità per i tuoi progetti",
      sec1P2:
        "SMART sviluppa progetti con il supporto di consulenti altamente qualificati, selezionati per la loro brillante esperienza nazionale e internazionale.",
      sec1H3: "Il tuo business ovunque, ora",
      sec1P3:
        "SMART è progettato per essere senza confini per collaborare con aziende di tutto il mondo.",
      sec1H4: "La combinazione perfetta per le tue esigenze ",
      sec1P4:
        "SMART non fornisce soluzioni preconfezionate, ma implementa un piano di sviluppo specifico, basato sulle esigenze del cliente.",
      sec1H5: "La strada ecologica",
      sec1P5:
        "SMART crede nelle nuove tecnologie e si rivolge ai migliori mercati per fornirti i migliori servizi per ridurre al minimo gli impatti ambientali.",
      sec1H6: 'Svelare il Potere dell IA',
      sec1p6: "SMART Rivoluziona i Flussi di Lavoro Digitali per tutti i progetti.",
      ad: 'Sede Legale: Viale Vittorio Veneto 80 presso Studio G.B., 59100 Prato (PO), Italia',
      ad1: 'Ufficio: Via G. Meoni 11, 59100 Prato (PO), Italia',
      ab_d1:
        "SMART è un azienda rivoluzionaria creata nel marzo 2015 dal visionario Emanuele Cecchi, con lobiettivo di potenziare le imprese in tutto il mondo.",
      ab_d2:
        "Forniamo una vasta gamma di servizi ai nostri clienti, contando su un team di consulenti altamente qualificati provenienti da vari paesi. Sono scelti per la loro vasta esperienza nei rispettivi settori e le loro abili capacità problem-solving, insieme alle partnership con i collaboratori internazionali di SMART.",
      ab_d3:
        "I nostri consulenti sono coinvolti strettamente con i clienti in ogni fase delle loro operazioni, collaborando fin dall inizio per sviluppare le strategie di miglioramento più adatte per creare opportunità di crescita.",
      sec1_end1: "Pronti per espandere i vostri orizzonti? ",
      sec1_end2: "Fate la scelta SMART.",
      ab_partner: "I nostri Partner:",
      ab_manager: "I nostri Country Managers:",
      ser_title1: "Consulenza Industriale",
      ser_desc1:
        "SMART è pronta a far crescere la tua attività! L'approccio ottimale inizia con la prenotazione di una consulenza con il nostro team per valutare le possibilità di mercato e sviluppare la strategia di internazionalizzazione più efficace. Il nostro team di consulenza assiste le aziende che cercano espansione e sviluppo oltreoceano, offrendo supporto qualificato e integrato nei mercati di destinazione.",
      ser_title2: "Temporary Export Manager",
      ser_desc2:
        "Un temporary export manager è un professionista dedicato a guidare la tua azienda nel mercato internazionale. Temporaneamente inserito nella tua azienda, il temporary export manager coltiva solide relazioni con altre imprese, i vostri possibili clienti, facilitando connessioni al di là dei tuoi confini. Con l'ausilio dei nostri collaboratori, partner e country manager, espandiamo i tuoi orizzonti e ti guidiamo verso le destinazioni desiderate attraverso un processo dinamico di internazionalizzazione.",
      ser_title3: "Didattica Aziendale",
      ser_desc3:
        "Emanuele Cecchi, il nostro visionario CEO e fondatore di SMART, è anche un brillante professore universitario. Con il suo patrimonio di esperienza, è pronto ad farti immergere nel mondo dei mercati e della gestione industriale.",
      ser_endT1: "Ancora curiosi?",
      ser_endT2: "Prenotate un appuntamento adesso!",
      team1_name: "Emanuele Cecchi",
      team1_pos: "Fondatore e Direttore Generale",
      team2_name: "Marialessandra Cecchi",
      team2_pos: "Specialista Linguistico",
      team3_name: "Chiara Storai",
      team3_pos: "Export Manager",
      team4_name: "Chiara Novelli",
      team4_pos: "Export Manager",
      cun: "CONTATTACI ORA",
      cun_title:
        "Compila il modulo qui sotto con la tua richiesta. Ti contatteremo presto!",
      cu_detail1: "SMART s.r.l.",
      cu_detail2: "C.S. € 10.000,00 i.v.",
      cu_detail3: "P.I e C.F. n° 06532350482",
      cu_detail4: "REA 635741",
      // cu_detail5: '',
      phone: "Telefono:",
      email: "Email: ",
      pec: "PEC:",
      ev: "Conferenze, Esposizioni, Eventi",
      tit1: "Francoforte, Germania",
      tit2: "Mosca, Russia",
      tit3: "San Pietroburgo, Russia",
      tit4: "Hanoi, Vietnam",
      tit5: "Il Cairo, Egitto",
      tit6: "Shenzen, Shanghai e Pechino, Cina",
      tit7: "Shanghai, Cina",
      tit8: "Pechino e Shanghai, Cina",
      tit9: "Singapore, Singapore",
      tit10: "Milano, Italia",
      tit11: "Barcellona, Spagna",
      tit12: "Prato, Italia",
      tit13: "Milano, Italia",
      tit14: "Parigi, Francia",
      tit15: "Milano, Bologna, Italia",
      tit16: "Bologna, Italia",
      tit17: "Düsseldorf, Germania",
      tit18: "Parigi, Francia",
      tit19: "Bologna, Italia",
      ser1_img1_text: 'Emanuele in un meeting con il Ministro dell Industria Egiziano',
      ser1_img2_text: 'Emanuele in un meeting con il Ministro dell Industria Russo',
      ser_head: "Emanuele Cecchi è un Manager dell'Innovazione riconosciuto e regolarmente iscritto sia alla lista ministeriale MIMIT (Ministero delle Imprese e del Made in Italy) che all'albo Unioncamere.",
      map_title: "Il nostro mondo SMART",
      map_desc: 'Siamo orgogliosi di mostrarvi tutte le nostre esperienze nei paesi del mondo',

    },
  },
  ru: {
    translation: {
      greeting: "ДОМ",
      ab: "О НАС",
      pt: "Партнеры",
      ser: "УСЛУГИ",
      ex: "ОПЫТ",
      cu: "СВЯЖИТЕСЬ С НАМИ",
      c: "Контакты",
      headerH: "Новые Горизонты для Вашего Бизнеса",
      headerP: "Конечное решение для расширения вашего бизнеса по всему миру.",
      sec1H1: "Вместе с вашими мечтами",
      sec1P1:
        "SMART специализируется на консалтинговых услугах для всех отраслей.",
      sec1H2: "Престиж, качество для ваших проектов",
      sec1P2:
        "SMART разрабатывает проекты с поддержкой высококвалифицированных консультантов, отобранных за свой блестящий национальный и международный опыт.",
      sec1H3: "Ваш бизнес везде, сейчас",
      sec1P3:
        "SMART создан для того, чтобы быть безграничным и сотрудничать с компаниями по всему миру.",
      sec1H4: "Идеальное сочетание для ваших потребностей",
      sec1P4:
        "SMART не предоставляет готовых решений, а реализует конкретный план развития, основанный на потребностях клиента.",
      sec1H5: "Экологический путь",
      sec1P5:
        "SMART верит в новые технологии и обращается к лучшим рынкам, чтобы обеспечить вас лучшими услугами для минимизации воздействия на окружающую среду.",
      sec1H6: 'Разблокирование силы ИИ',
      sec1p6: "SMART Революционизирует цифровые рабочие процессы для всех проектов.",
      ad: 'Штаб-квартира: Виале Витторио Венето 80, студия G.B., 59100 Прато (ПО), Италия',
      ad1: 'Офис: Виа Дж. Меони 11, 59100 Прато (ПО), Италия',
      ab_d1:
        "SMART - революционная компания, созданная в марте 2015 года визионером Эмануэле Чекки с целью улучшения бизнеса по всему миру.",
      ab_d2:
        "Мы предоставляем широкий спектр услуг нашим клиентам, полагаясь на команду высококвалифицированных консультантов из разных стран. Они выбираются за свой обширный опыт в своих областях и их умения в решении проблем, а также за партнерство с международными союзниками SMART.",
      ab_d3:
        "Наши консультанты тесно сотрудничают с клиентами на всех этапах их деятельности, начиная с самого начала, чтобы разработать наиболее подходящие стратегии улучшения и создать возможности для роста.",
      sec1_end1: "Готовы расширить свои горизонты?",
      sec1_end2: "Сделайте умный выбор - SMART.",
      ab_partner: "Наши Партнёры:",
      ab_manager: "Наши Менеджеры по странам",
      ser_title1: "Промышленное Консультирование",
      ser_desc1:
        "Промышленное консультирование SMART готова помочь вашему бизнесу вырасти! Оптимальный подход начинается с назначения консультации с нашей командой для оценки рыночных возможностей и разработки наиболее эффективной интернационализацой стратегии.Наша консультационная команда помогает компаниям, ищущим расширение и развитие за рубежом, предлагая квалифицированную и интегрированную поддержку на целевых рынках.",
      ser_title2: "Временное Управление Экспортом",
      ser_desc2:
        "Временный менеджер по экспорту - это профессионал, посвятивший себя руководству вашей компании на международном рынке. Временно вступая в вашу компанию, менеджер по экспорту развивает крепкие отношения с другими предприятиями, своими потенциальными клиентами, облегчая связи за пределами ваших границ. С помощью наших партнеров, соучастников и менеджеров по странам мы расширяем ваши горизонты и направляем вас к желаемым направлениям через динамичный процесс интернационализации.",
      ser_title3: "Промышленное Обучение",
      ser_desc3:
        "Эмануэле Чекки, наш видящий в будущее CEO и основатель SMART, также является блестящим профессором университета. С его богатым опытом, он готов погрузить вас в мир рынков и промышленного менеджмента.",
      ser_endT1: "Ещё интересно?",
      ser_endT2: "Запишитесь на приём к нам прямо сейчас!",
      team1_name: "Emanuele Cecchi",
      team1_pos: "Основатель и Генеральный Директор",
      team2_name: "Marialessandra Cecchi",
      team2_pos: "Лингвистический специалист",
      team3_name: "Chiara Storai",
      team3_pos: "Менеджер по экспорту",
      team4_name: "Менеджер по экспорту",
      team4_pos: "Export Manager",
      cun: "СВЯЖИТЕСЬ С НАМИ СЕЙЧАС",
      cun_title:
        "Заполните форму ниже своим запросом. Мы свяжемся с вами в ближайшее время!",
      cu_detail1: "SMART s.r.l.",
      cu_detail2: "C.C. € 10.000,00 у.в.",
      cu_detail3: "ИНН и Код Ф. 06532350482",
      cu_detail4: "РЕА 635741",
      // cu_detail5: '',
      phone: "Телефон:",
      email: "Эл. почта:",
      pec: "PEC: ",
      ev: "Конференции, Мероприятия, Выставки",
      tit1: "Франкфурт, Германия",
      tit2: "Москва, Россия",
      tit3: "Санкт-Петербург, Россия",
      tit4: "Ханой, Вьетнам",
      tit5: "Каир, Египет",
      tit6: "Шэньчжэнь, Шанхай и Пекин, Китай",
      tit7: "Шанхай, Китай",
      tit8: "Пекин и Шанхай, Китай",
      tit9: "Сингапур, Сингапур",
      tit10: "Милан, Италия",
      tit11: "Барселона, Испания",
      tit12: "Прато, Италия",
      tit13: "Милан, Италия",
      tit14: "Париж, Франция",
      tit15: "Милан, Болонья, Италия",
      tit16: "Болонья, Италия",
      tit17: "Дюссельдорф, Германия",
      tit18: "Париж, Франция",
      tit19: "Болонья, Италия",
      ser1_img1_text: 'Эмануэль на встрече с Министром Промышленности Египта',
      ser1_img2_text: 'Эмануэль на встрече с Министром Промышленности России',
      ser_head: "Эмануэле Чекки является признанным менеджером по инновациям и регулярно занесен в список МИМИТ (Министерство Предприятий и Сделано в Италии) и в реестр Unioncamere.",
      map_title: "Наш мир SMART",
      map_desc: 'Мы гордимся тем, что делимся всеми нашими опытами в странах мира',
    },
  },
  es: {
    translation: {
      greeting: "INICIO",
      ab: "SOBRE NOSOTROS",
      pt: "Socios",
      ser: "SERVICIOS",
      ex: "EXPERIENCIAS",
      cu: "Contáctenos",
      c: "Contactos",
      headerH: "Nuevos Horizontes para su Empresa",
      headerP:
        "La solución definitiva para expandir tu negocio a nivel mundial.",
      sec1H1: "Junto con tus sueños",
      sec1P1:
        "SMART se especializa en servicios de consultoría para todas las industrias.",
      sec1H2: "Prestigio, calidad para tus proyectos",
      sec1P2:
        "SMART desarrolla proyectos con el apoyo de consultores altamente calificados, seleccionados por su brillante experiencia nacional e internacional.",
      sec1H3: "Tu empresa en todas partes, ahora",
      sec1P3:
        "SMART está diseñado para ser sin fronteras y colaborar con empresas de todo el mundo.",
      sec1H4: "La combinación perfecta para tus necesidades",
      sec1P4:
        "SMART no proporciona soluciones preempaquetadas, sino que implementa un plan de desarrollo específico, basado en las necesidades del cliente.",
      sec1H5: "El camino ecológico",
      sec1P5:
        "SMART cree en las nuevas tecnologías y se dirige a los mejores mercados para proporcionarte los mejores servicios para minimizar los impactos ambientales.",
      sec1H6: 'Liberando el Poder de la IA',
      sec1p6: "SMART Revoluciona los Flujos de Trabajo Digitales para todos los proyectos.",
      ad: 'Sede Principal: Viale Vittorio Veneto 80 en el Estudio G.B., 59100 Prato (PO), Italia',
      ad1: 'Oficina: Via G. Meoni 11, 59100 Prato (PO), Italia',
      ab_d1:
        "SMART es una empresa revolucionaria creada en marzo de 2015 por el visionario Emanuele Cecchi, con el objetivo de mejorar los negocios en todo el mundo.",
      ab_d2:
        "Ofrecemos una amplia gama de servicios a nuestros clientes, contando con un equipo de consultores altamente calificados de diversos países. Son elegidos por su amplia experiencia en sus respectivos campos y sus habilidades expertas para resolver problemas, junto con asociaciones con colaboradores internacionales de SMART.",
      ab_d3:
        "Nuestros consultores se involucran estrechamente con los clientes en cada fase de sus operaciones, colaborando desde el principio para desarrollar las estrategias de mejora más adecuadas y crear oportunidades de crecimiento.",
      sec1_end1: "¿Listos para expandir sus horizontes?",
      sec1_end2: "Hagan la elección SMART.",
      ab_partner: "Nuestros Socios:",
      ab_manager: "Nuestros Gerentes de País:",
      ser_title1: "Consultoría Industrial",
      ser_desc1:
        "¡SMART está lista para hacer crecer tu negocio! El enfoque óptimo comienza con la programación de una consulta con nuestro equipo para evaluar las posibilidades del mercado y elaborar la estrategia de internacionalizaciónmás efectiva. Nuestro equipo de consultoría asiste a las empresas que buscan expansión y desarrollo en el extranjero, ofreciendo apoyo cualificado e integrado en los mercados de destino.",
      ser_title2: "Gestión Temporal de Exportaciones",
      ser_desc2:
        "Un gerente de exportaciones temporal es un profesional dedicado a guiar a su empresa en el mercado internacional. Insertado temporalmente en su empresa, el gerente de exportaciones cultiva relaciones sólidas con otras empresas, sus posibles clientes, facilitando conexiones más allá de sus fronteras. Con la ayuda de nuestros colaboradores, socios y gerentes de país, ampliamos sus horizontes y lo guiamos hacia los destinos deseados a través de un proceso dinámico de internacionalización.",
      ser_title3: "Educación Industrial",
      ser_desc3:
        "Emanuele Cecchi, nuestro visionario CEO y fundador de SMART, también es un brillante profesor universitario. Con su vasta experiencia, está listo para sumergirte en el mundo de los mercados y la gestión industrial.",
      ser_endT1: "¿Aún tienes curiosidad?",
      ser_endT2: "¡Programa una cita con nosotros ahora mismo!",
      team1_name: "Emanuele Cecchi",
      team1_pos: "Fundador y Director General",
      team2_name: "Marialessandra Cecchi",
      team2_pos: "Especialista Lingüístico",
      team3_name: "Chiara Storai",
      team3_pos: "Gerente de Exportación",
      team4_name: "Chiara Novelli",
      team4_pos: "Gerente de Exportación",
      cun: "CONTÁCTANOS AHORA",
      cun_title:
        "Completa el formulario que se encuentra a continuación con tu solicitud. ¡Nos pondremos en contacto contigo pronto!",
      cu_detail1: "SMART s.r.l.",
      cu_detail2: "C.S. € 10.000,00 i.v.",
      cu_detail3: "P.I y C.F. n° 06532350482",
      cu_detail4: "REA 635741",
      // cu_detail5: '',
      phone: "Teléfono:",
      email: "Correo electrónico:",
      pec: "PEC:",
      ev: "Conferencias, Eventos, Exposiciones",
      tit1: "Fráncfort, Alemania",
      tit2: "Moscú, Rusia",
      tit3: "San Petersburgo, Rusia",
      tit4: "Hanoi, Vietnam",
      tit5: "El Cairo, Egipto",
      tit6: "Shenzhen, Shanghái y Pekín, China",
      tit7: "Shanghái, China",
      tit8: "Pekín y Shanghái, China",
      tit9: "Singapur, Singapur",
      tit10: "Milán, Italia",
      tit11: "Barcelona, España",
      tit12: "Prato, Italia",
      tit13: "Milán, Italia",
      tit14: "París, Francia",
      tit15: "Milán, Bolonia, Italia",
      tit16: "Bolonia, Italia",
      tit17: "Düsseldorf, Alemania",
      tit18: "París, Francia",
      tit19: "Bolonia, Italia",
      ser1_img1_text: 'Emanuele en una reunión con el Ministro de Industria Egipcio',
      ser1_img2_text: 'Emanuele en una reunión con el Ministro de Industria Ruso',
      ser_head: "Emanuele Cecchi es un Gerente de Innovación reconocido y regularmente inscrito tanto en la lista ministerial MIMIT (Ministerio de Empresas y Hecho en Italia) como en el registro de Unioncamere.",
      map_title: "Nuestro mundo SMART",
      map_desc: 'Estamos orgullosos de mostrar todas nuestras experiencias en los países del mundo',
    },
  },
};

i18n.use(initReactI18next).init({
  resources,
  lng: "en",
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;
